name: Playwright Tests

on:
  schedule:
    - cron: "0 0 1 * *"  # Runs on the 1st of every month
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:  # Allows manual triggering

jobs:
  playwright_tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      
      # Checkout repository
      - uses: actions/checkout@v4

      # --- Playwright Setup & Execution ---
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Playwright Dependencies
        run: npm install  # Changed from `npm ci` to `npm install`

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30